- hosts: win_agents
  tasks:
    - include_vars: group_vars/agents
    - import_tasks: roles/windows/deploy_dns.yml
    - import_tasks: roles/agents/deploy_osquery_windows.yml
    - include_vars: group_vars/win_dc
    - import_tasks: roles/windows/join_windows_to_domian.yml
