####################################################################
# Set hostname
####################################################################
- name: add hostname to /etc/hosts
  lineinfile:
   dest: /etc/hosts
   regexp: '^127\.0\.0\.1[ \t]+localhost'
   line: '127.0.0.1 localhost {{ caldera_hostname }} {{ caldera_hostname }}.{{ base_domain }}'
   state: present
- hostname:
   name: "{{ caldera_hostname }}.{{ base_domain }}"

####################################################
# Install/Setup Caldera
####################################################
- name: Install software
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - python3-dev
    - python3-pip

- name: Create Caldera user
  user:
    name: caldera
    shell: /usr/sbin/nologin

- name: Download caldera
  git:
    repo: 'https://github.com/mitre/caldera.git'
    dest: '{{ caldera_dir }}'
- file:
    path: '{{ caldera_dir }}'
    recurse: yes
    state: directory
    owner: caldera
    group: caldera

- name: SED aiohttp==2.3.2 to aiohttp==2.3.8
  lineinfile:
    path: '{{ caldera_dir }}/caldera/requirements.txt'
    regexp: '^aiohttp==2.3.2'
    line: 'aiohttp==2.3.8'

- name: Pip requirements.txt
  pip:
    requirements: '{{ caldera_dir }}/caldera/requirements.txt'
    executable: pip3

- name: Create directory for CraterMain.exe
  file:
    path: '{{ caldera_dir }}/dep/crater/crater'
    state: directory
    owner: caldera
    group: caldera
    mode: 0755

- name: Download CraterMain.exe for Win8 and up
  get_url:
    url: https://github.com/mitre/caldera-crater/releases/download/v0.1.0/CraterMainWin8up.exe
    dest: '{{ caldera_dir }}/dep/crater/crater/CraterMain.exe'
    validate_certs: no

#- name: Copy Caldera settings.yaml
#  template:
#    src: conf/caldera/settings.yaml.default
#    dest: '{{ caldera_dir }}/caldera/conf/settings.yaml.default'

- name: Copy SystemD file
  template:
    src: conf/caldera/caldera.service
    dest: /etc/systemd/system/caldera.service

- name: Start caldera service
  service:
    name: caldera
    state: restarted
    enabled: yes
