####################################################################
# Install/Setup MongoDB
####################################################################
- name: Install MongoDB
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - mongodb-server

- name: Copy Mongo conf
  template:
    src: conf/mongo/mongodb.conf
    dest: /etc/mongodb.conf

- name: Start Mongo service
  service:
    name: mongodb
    state: restarted
    enabled: yes
