version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - .:/tmp
    command: mysqld --datadir=/tmp/mysqldata --slow_query_log=1 --log_output=TABLE --log-queries-not-using-indexes
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: kolide
      MYSQL_USER: kolide
      MYSQL_PASSWORD: kolide
    ports:
      - "3306:3306"

  mysql_test:
    image: mysql:5.7
    command: mysqld --datadir=/tmpfs  --slow_query_log=1 --log_output=TABLE --log-queries-not-using-indexes
    tmpfs: /tmpfs
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: kolide
      MYSQL_USER: kolide
      MYSQL_PASSWORD: kolide
    ports:
      - "3307:3306"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:3.2.4
    ports:
      - "6379:6379"

  fleet:
    image: kolide/fleet
    ports:
      
