####################################################################
# Create doorman user
####################################################################
- name: Create doorman unix user
  user:
    name: doorman

####################################################################
# Install/Setup Doorman
####################################################################
- name: Install/Setup Doorman
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - python3-pip
    - python3-dev
    - libffi-dev
    - gcc
    - postgresql-server-dev-9.6
    - nodejs
    - uwsgi
    - uwsgi-plugin-python3
    - npm

- name: Update Pip
  pip:
    name: pip
    executable: pip3
    extra_args: --upgrade

- name: Download Doorman repo
  git:
    repo: https://github.com/mwielgoszewski/doorman.git
    dest: /opt/doorman
  ignore_errors: True

- name: Chown doorman directory to doorman user
  file:
    path: /opt/doorman
    owner: doorman
    group: doorman
    state: directory
    recurse: yes

- name: Install virtualenv and pexpect
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - virtualenv
    - pexpect

- name: Create virtualenv as Doorman user and install requirements
  pip:
    requirements: /opt/doorman/requirements.txt
    virtualenv: /opt/doorman/env
    virtualenv_python: python3.5
  become: true
  become_user: doorman
- pip:
    name: '{{ item }}'
    virtualenv: /opt/doorman/env
  with_items:
    - flask
  become: true
  become_user: doorman

- name: Chown doorman directory to doorman user
  file:
    path: /opt/doorman
    owner: doorman
    group: doorman
    state: directory
    recurse: yes

- name: Create Doorman logging directory
  file:
    path: /var/log/doorman
    owner: doorman
    group: doorman
    state: directory
    recurse: yes

- name: Copy Doorman settings.py config
  template:
    src: conf/doorman/settings.py
    dest: /opt/doorman/doorman/settings.py
    owner: doorman
    group: doorman
    mode: 0644

- name: Copy Doorman uwsgi config
  template:
    src: conf/doorman/doorman.ini
    dest: /opt/doorman/doorman.ini
    owner: doorman
    group: doorman
    mode: 0644

- name: Set env var to production
  lineinfile:
    dest: /etc/profile
    line: export DOORMAN_ENV=prod
- shell: "echo $DOORMAN_ENV"

- name: Initialize doorman env variables
  shell: env/bin/python manage.py db upgrade
  args:
    chdir: /opt/doorman
  become: true
  become_user: doorman
  become_method: sudo
  environment:
    DOORMAN_ENV: '{{ doorman_mode }}'

- name: Add Doorman local user
  expect:
    command: "env/bin/python manage.py adduser {{ doorman_webgui_user }}"
    responses:
      (?i)Password*: "{{ doorman_webgui_pass }}"
    chdir: /opt/doorman
  become: true
  become_user: doorman
  become_method: sudo
  environment:
    DOORMAN_ENV: '{{ doorman_mode }}'
  register: fail_me
  failed_when: "'Username already exists' not in fail_me.stdout"

- name: Install nodejs components
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - bower
    - less

- name: Create sym link
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    owner: doorman
    group: doorman
    state: link

- name: Install bower components
  bower:
    path: /opt/doorman
  become: true
  become_user: doorman
  become_method: sudo

- name: Set correct path for interact.js
  lineinfile:
    regexp: '^libs/interact/interact.js'
    line: 'libs/interact/src/interact.js'

####################################################################
# Install/Setup Nginx + wsgi/flask + OpenSSL
####################################################################
- name: Install Nginx
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - nginx

- name: Backup NGINX config
  shell: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

- name: Create NGINX SSL directory
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Generate DH key
  stat:
    path: /etc/nginx/ssl/dhparam.pem
  register: stat_dhparam
- shell: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
  when: stat_dhparam.stat.exists == False

- name: Create OpenSSL custom cert for Doorman
  shell: openssl req -new -nodes -x509 -days 3650 -subj "/C={{ cert_country }}/ST={{ cert_state }}/L={{ cert_local }}/O={{ cert_org }}/CN={{ doorman_hostname }}.{{ base_domain }}" -keyout /etc/nginx/ssl/private.key -out /etc/nginx/ssl/certificate.crt
  when: stat_dhparam.stat.exists == False

- template:
    src: conf/nginx/nginx_doorman.conf
    dest: /etc/nginx/conf.d/nginx_doorman.conf
    owner: root
    group: root
    mode: '0600'

- template:
    src: conf/doorman/doorman.service
    dest: /etc/systemd/system/doorman.service
    owner: root
    group: root
    mode: '0600'

####################################################################
# Restart Nginx and doorman service
####################################################################
- name: Start Nginx and Doorman service
  service:
    name: '{{ item }}'
    state: restarted
    enabled: yes
  with_items:
    - doorman
    - nginx

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Finished setting up Doorman - {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token is undefined
