####################################################################
#  Promote Windows Server to Domain controller
####################################################################
- name: Install AD Domain Services
  win_feature:
    name: 'AD-Domain-Services'
    state: present
    #reboot_required: True
    #restart_needed: True
    include_management_tools: yes
    include_sub_features: yes

- name: Promote to domain controller
  win_domain:
    dns_domain_name: '{{ ad_domain_name }}'
    safe_mode_password: '{{ ad_safe_mode_password }}'
  register: active_directory_controllers

- name: reboot once DC created
  win_reboot:
  when: active_directory_controllers.reboot_required

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Promoted {{ ansible_nodename }} to domain controller of {{ ad_domain_name }} domain'
    channel: "{{ slack_channel }}"
  when: slack_token is undefined
